* hub dir https://hgwdev.gi.ucsc.edu/~markd/lrgasp/experimental-eval/hub/hg38/dir/
* IGV tracks
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/targets.bb
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.98.genome.bam
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.95.genome.bam
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.90.genome.bam

* Gloria spread sheet
https://docs.google.com/spreadsheets/d/1nW8W_xtfvKE1sSDBNRsZ3K6HWEtxb4jWwZtPh5hNMVA/edit#gid=0

* JuJu spread sheet
https://docs.google.com/spreadsheets/d/1Y3KhZoezR8Ti5mauYXQFxuwE04xmEgPPyxoJoRxuYuA/edit#gid=210377221


* ALG6+1
All models are bad. Intron 3' end at chr1:63,411,128-63,411,194 has GT-AT
splice site.  This is a documented U12 intron, but with a very rare splicing
pattern.  Supported by WTC-11 reads. GENCODE and RefSeq.  Models and minimap2
seemed to have force GT-AG 6 bases upstream by calling an intron +
target-insertion (D).

* ARPC2+1 (287pb
Lots of 100% amplicon support, but no chain support.
Exon at chr2:218,217,459-218,217,545 is include in all chains, but not in target.
How is it possible


* debugging:
 ../../../bin/genomeAlignAnalyze --target=DUSP4+C ../../../hub/hg38/juju_designs.hg38.isoforms.tsv ../../../hub/hg38/targets.bed  ../align/pb-rna-wtc11-genome.bam debug.tsv --supportBam=debug.bam &


* ID3+1 chr1:23558247-23559143
looks like there are reads confirming splice sites, but only a few reported

** samtools view ../align/pb-rna-wtc11-genome.bam chr1:23558247-23559143 > ID3+1.pb.sam
8501 ID3+1.pb.sam

*** these look like they should support:

Read name = m64152e_230121_000958/105972269/ccs
Read length = 2,908bp
Cigar = 760S233M519N85M107N25M1D277M1D158M1370S
Clipping = Left 760 soft; Right 1,370 soft
SupplementaryAlignments
chr10:95,238,611-95,290,909 (-) = 52,298bp  @MAPQ 60 NM1
chr1:159,918,758-159,925,470 (-) = 6,712bp  @MAPQ 57 NM2
chr3:39,407,709-39,411,993 (+) = 4,284bp  @MAPQ 1 NM4

countSupport: ID3+1 NNC_380057 ((23558415, 23558934), (23559010, 23559114))
  [nosupport] m64152e_230121_000958/105972269/ccs ((23558415, 23558934), (23559019, 23559126)) 

two possible accept AG acceptors, 9 bases apart


Read name = m64152e_230121_000958/171837960/ccs
Read length = 1,050bp
Reference span = chr1:23,557,921-23,559,499 (+) = 1,579bp
Cigar = 53S495M519N85M107N373M44S
Clipping = Left 53 soft; Right 44 soft

