* hub dir https://hgwdev.gi.ucsc.edu/~markd/lrgasp/experimental-eval/hub/hg38/dir/
* IGV tracks
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/targets.bb
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.98.genome.bam
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.95.genome.bam
https://hgwdev.gi.ucsc.edu/~markd/gencode/lrgasp/experimental-eval/hub/hg38/pb+ont-rna-wtc11.sim=0.90.genome.bam

* Gloria spread sheet
https://docs.google.com/spreadsheets/d/1nW8W_xtfvKE1sSDBNRsZ3K6HWEtxb4jWwZtPh5hNMVA/edit#gid=0

* JuJu spread sheet
https://docs.google.com/spreadsheets/d/1Y3KhZoezR8Ti5mauYXQFxuwE04xmEgPPyxoJoRxuYuA/edit#gid=210377221


* ALG6+1
All models are bad. Intron 3' end at chr1:63,411,128-63,411,194 has GT-AT
splice site.  This is a documented U12 intron, but with a very rare splicing
pattern.  Supported by WTC-11 reads. GENCODE and RefSeq.  Models and minimap2
seemed to have force GT-AG 6 bases upstream by calling an intron +
target-insertion (D).

* ARPC2+1 (287pb
Lots of 100% amplicon support, but no chain support.
Exon at chr2:218,217,459-218,217,545 is include in all chains, but not in target.
How is it possible


* debugging:
 ../../../bin/genomeAlignAnalyze --target=DUSP4+C ../../../hub/hg38/juju_designs.hg38.isoforms.tsv ../../../hub/hg38/targets.bed  ../align/pb-rna-wtc11-genome.bam debug.tsv --supportBam=debug.bam &


* ID3+1 chr1:23558247-23559143
looks like there are reads confirming splice sites, but only a few reported

** samtools view ../align/pb-rna-wtc11-genome.bam chr1:23558247-23559143 > ID3+1.pb.sam
8501 ID3+1.pb.sam



* DGAT2+D	ENST00000705697
Unclear why exon at chr11:75,790,178-75,790,305 is not called by minimap2. Reads locally support exon, but not chained. Many supplementary alignments. Short, secondary alignments on amplicon.

** PB:
Read name = m64152e_230121_000958/113050968/ccs
Read length = 1,820bp
Flags = 16
----------------------
Mapping = Primary @ MAPQ 60
Reference span = chr11:75,768,994-75,796,447 (-) = 27,454bp
Cigar = 1273S 119M 15505N 129M 5441N 108M 365N 71M 5596N 120M 
Clipping = Left 1,273 soft
----------------------
EXON    75790178        75790305

% cigar_coordinates -d - -c 119M15505N129M5441N108M365N71M5596N120M -s 75768994
120M    75768994        75769113
5596N   75769114        75774709
71M     75774710        75774780
365N    75774781        75775145
108M    75775146        75775253
5441N   75775254        75780694
129M    75780695        75780823
15505N  75780824        75796328
  EXON    75790178        75790305
119M    75796329        75796447

** 
